<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_handle</name>
   <tag></tag>
   <elementGuidId>e6a8a8c1-0dc4-4bf0-9187-e1810f60935f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>handle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;node_map&quot;)/div[@class=&quot;all&quot;]/div[@class=&quot;Home normal_width&quot;]/div[@class=&quot;right-top&quot;]/div[1]/button[@class=&quot;_simple-switch-track&quot;]/span[@class=&quot;handle&quot;]</value>
   </webElementProperties>
</WebElementEntity>
